### PR TITLE
Using Homegrown Elasticsearch Role

### PR DESCRIPTION
**Pull request by vforgione**
1. elastic's ansible role is broke as fuck
1. their role, even when "fixed" won't install a proper 5.x
1. this follows the official docs from elastic
1. it works!

### CODE REVIEW

**Comment by ajrgrubbs** [comment]
My vagrant test fails with the following error:

```
TASK [elasticsearch : starting elasticsearch] **********************************
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME\n"}
```

The reason is obvious: Java isn't installed on my clean vagrant VM.

Either the role should apt-get java or the dependency should be documented.

**Comment by vforgione** [comment]
I'm leaning more to installing java since it requires Oracle 8. OpenJDK is supported but it's a massive pain on 14.04 jetting the right version.

**Comment by vforgione** [comment]
@ajrgrubbs, I updated the ES role. Try it again.

**Comment by adamyala** [comment]
👍

**Pull request merged**
