### PR TITLE
Adding cassandra role

### PR DESCRIPTION
**Pull request by Prajaktcs**
cd into example folder and do vagrant up
When the machine starts, you could check that cassandra is running by ps aux | grep cassandra

### CODE REVIEW

**Comment by emmanuellyautomated** [comment]
ran into this error:

```
==> cassandra: Running provisioner: ansible...
    cassandra: Running ansible-playbook...
 [WARNING]: Optional dependency 'cryptography' raised an exception, falling
back to 'Crypto'

ERROR! 'listen' is not a valid attribute for a Handler

The error appears to have been in '/Users/emmanuel/5thcolumn/ansible/5c-roles/cassandra/handlers/main.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Start cassandra service
  ^ here

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by Prajaktcs** [comment]
@emmanuellyautomated I found out that listen doesnot work below ansible 2.2

**Comment by ajrgrubbs** [comment]
Had to add `run_mode: install` to `run.yml` to get this to work.

👍

**Comment by Prajaktcs** [comment]
@ajrgrubbs Yes, i was testing it out and forgot to change it back to install. Thanks 👍 . I will set it back to install in the defaults file.

**Comment by Prajaktcs** [comment]
@ajrgrubbs done

**Pull request merged**
