### PR TITLE
Adding Jupyter Notebook Role

### PR DESCRIPTION
**Pull request by vforgione**
Adding the famous @jmcarlock jupyter notebook role.

Let's try this again...

### CODE REVIEW

**Comment by ajrgrubbs** [comment]
For the record, this role requires the latest version of Ansible (v2.2). Otherwise the unarchive step doesn't know how to download the file.

The role also needs root permissions, but it looks for the home directory at `/home/USERNAME` which is not standard for the root user (who usually resides at `/root`)

**Comment by jmcarlock** [comment]
👍

**Comment by vforgione** [comment]
@ajrgrubbs i'm in the process of changing our roles to only use root when needed - it screws up a lot of stuff.

**Comment by adamyala** [comment]
👍

**Pull request merged**
