### PR TITLE
Updated uwsgi-* to latest

### PR DESCRIPTION
**Pull request by vforgione**

### CODE REVIEW

**Comment by adamyala** [comment]
👍

**Comment by adamyala** [comment]
I'm attempting to build the most recent master of frontloader. I deleted my 5c-roles folder, cloned it down fresh. Checked out this branch, then initialized the submodules. I get the below ever when trying to spin up a vagrant box
```
TASK [uwsgi-emperor : installing uwsgi] ****************************************
fatal: [default]: FAILED! => {"changed": true, "cmd": ["python3.5", "-m", "pip", "install", "uwsgi", "--update"], "delta": "0:00:00.318561", "end": "2016-12-08 19:38:54.937619", "failed": true, "rc": 2, "start": "2016-12-08 19:38:54.619058", "stderr": "\nUsage:   \n  /usr/bin/python3.5 -m pip install [options] <requirement specifier> [package-index-options] ...\n  /usr/bin/python3.5 -m pip install [options] -r <requirements file> [package-index-options] ...\n  /usr/bin/python3.5 -m pip install [options] [-e] <vcs project url> ...\n  /usr/bin/python3.5 -m pip install [options] [-e] <local project path> ...\n  /usr/bin/python3.5 -m pip install [options] <archive url/path> ...\n\nno such option: --update", "stdout": "", "stdout_lines": [], "warnings": []}
```

**Comment by adamyala** [comment]
In `command: python{{ python_version }} -m pip install uwsgi --update` I removed `--update` and it works. Should that be changed?

**Comment by vforgione** [comment]
@adamyala yes. please open an issue on the repo

**Pull request merged**
