### PR TITLE
change git url for logstash submodule

### PR DESCRIPTION
**Pull request by emmanuellyautomated**

### CODE REVIEW

**Comment by vforgione** [comment]
Much better. Can you update the README in your role with some info about the changes you made in your fork and why we should use it instead of the upstream from geerlingguy?

**Comment by emmanuellyautomated** [comment]
@vforgione, will do. I basically just replaced his conf templates with some that we'll be using so that we can interpolate them with client data.

**Comment by emmanuellyautomated** [comment]
@vforgione: I've added that explanation to the [readme](https://github.com/emmanuellyautomated/ansible-role-logstash/blob/master/README.md).

**Comment by emmanuellyautomated** [comment]
@dan; @vforgione: I've pointed the submodule to the appropriate repo.

**Pull request merged**
